import Link from 'next/link'
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import { isPublishableGrant } from '@/lib/quality'
import { eligibilityLabels } from '@/lib/eligibility'
import { slugify } from '@/lib/slug'
import { SITE_URL, OG_IMAGE } from '@/lib/site'
import TrackedLink from '@/app/components/TrackedLink'
import BackLink from '@/app/components/BackLink'
import GrantList, { type GrantListItem } from '@/app/components/GrantList'

export const dynamic = 'force-dynamic'

/**
 * A grant's own page.
 *
 * This is the front door from search. The list at /grants is drawn in the
 * browser, so a crawler sees nothing there; this page ships the full grant in
 * plain HTML, at a stable address, which is what a search engine can rank and
 * what an AI answer engine can cite.
 *
 * Honesty is enforced the same way it is on the card: a closed or broken grant
 * is still reachable by its link but marked "do not index", so we never rank a
 * page for an opportunity nobody can apply to, and never send a searcher from
 * Google to a dead end.
 *
 * Slugs are matched from the grant name for now. When the slug column lands in
 * phase one this switches to a direct lookup; the URLs stay identical because
 * they are generated by the same slugify().
 */

const COLUMNS =
  'id,name,funder,funder_id,institution_id,amount,deadline,deadline_type,cci_sector,funding_type,' +
  'eligible_countries,eligible_who,eligible_conditions,eligibility_reviewed,' +
  'application_link,description,link_state,link_checked_at'

type Grant = {
  id: string
  name: string
  funder: string | null
  funder_id: string | null
  institution_id: string | null
  amount: string | null
  deadline: string | null
  deadline_type: string | null
  cci_sector: string | null
  funding_type: string | null
  eligible_countries: string[] | null
  eligible_who: string | null
  eligible_conditions: string | null
  eligibility_reviewed: boolean | null
  application_link: string | null
  description: string | null
  link_state: string | null
  link_checked_at: string | null
}

const WHO_LABEL: Record<string, string> = {
  individual: 'Individuals',
  organisation: 'Registered organisations',
  either: 'Individuals or organisations',
  partnership: 'Applicants with a partner',
}

/**
 * Find a publishable grant by its slug.
 *
 * The fast path is the stored slug column — one indexed row. Older grants
 * whose slug has not been backfilled yet, and any edge case, fall back to
 * matching the slug derived from the name, so no URL breaks during the
 * backfill. Both paths generate the identical URL, so a grant's address never
 * changes as it crosses from one to the other.
 */
async function grantBySlug(slug: string): Promise<Grant | null> {
  const direct = await supabase
    .from('opportunities')
    .select(COLUMNS)
    .eq('slug', slug)
    .not('description', 'is', null)
    .maybeSingle()
  if (direct.data) {
    const g = direct.data as unknown as Grant
    if (isPublishableGrant(g)) return g
  }

  const { data } = await supabase.from('opportunities').select(COLUMNS).not('description', 'is', null)
  const rows = ((data as unknown as Grant[]) ?? []).filter(isPublishableGrant)
  return rows.find((g) => slugify(g.name) === slug) ?? null
}

function daysLeft(deadline: string | null): number | null {
  if (!deadline) return null
  const d = new Date(deadline)
  if (isNaN(d.getTime())) return null
  return Math.ceil((d.getTime() - Date.now()) / 86_400_000)
}

/** A one-line description of the funder, and a link to their profile. */
async function funderBlurb(
  institutionId: string | null,
): Promise<{ name: string; slug: string | null; description: string | null } | null> {
  if (!institutionId) return null
  const { data } = await supabase
    .from('funders')
    .select('name, slug, description')
    .eq('id', institutionId)
    .maybeSingle()
  return (data as { name: string; slug: string | null; description: string | null }) ?? null
}

const RELATED_COLUMNS = 'id,name,slug,funder,institution_id,funding_type,cci_sector,deadline,deadline_type,eligible_countries,description,link_state'

/**
 * Other opportunities worth seeing from this page: the same funder's other
 * calls, and open calls in the same sector or country. Only open, working,
 * publishable grants — never a closed or dead one — and never this grant itself.
 * Every row is a real grant already in the database; nothing is invented.
 */
async function relatedGrants(
  g: Grant,
): Promise<{ fromFunder: GrantListItem[]; related: GrantListItem[] }> {
  const { data } = await supabase
    .from('opportunities')
    .select(RELATED_COLUMNS)
    .not('description', 'is', null)
    .neq('id', g.id)
  type Row = GrantListItem & {
    id: string
    institution_id?: string | null
    eligible_countries: string[] | null
    description: string | null
    link_state: string | null
  }
  const open = ((data as unknown as (Row & { institution_id?: string | null })[]) ?? [])
    .filter((r) => isPublishableGrant(r as { name: string; description?: string | null }))
    .filter((r) => r.link_state !== 'dead')
    .filter((r) => {
      const dl = daysLeft(r.deadline)
      return dl === null || dl >= 0 // hide calls whose fixed deadline has passed
    })

  // Siblings share the funder profile (institution_id), even though their
  // free-text funder name can differ ("Goethe-Institut" vs "Goethe-Institut /
  // partners"). Match on the profile, not the name.
  const sameFunder = (r: { institution_id?: string | null }) =>
    g.institution_id != null && r.institution_id === g.institution_id
  const fromFunder = open.filter(sameFunder).slice(0, 4)

  const country = (g.eligible_countries ?? [])[0]
  const related = open
    .filter((r) => !sameFunder(r)) // not the same funder (those are shown above)
    .filter(
      (r) =>
        (g.cci_sector && r.cci_sector === g.cci_sector) ||
        (country && (r.eligible_countries ?? []).includes(country)),
    )
    .slice(0, 5)

  return { fromFunder, related }
}

/** Closed (a fixed deadline has passed) or its link is dead: keep the page, hide it from search. */
function shouldIndex(g: Grant): boolean {
  const dl = daysLeft(g.deadline)
  if (dl !== null && dl < 0) return false
  if (g.link_state === 'dead') return false
  return true
}

function deadlineText(g: Grant): string | null {
  if (g.deadline_type === 'rolling') return 'Rolling — no fixed deadline'
  if (!g.deadline) return g.deadline_type === 'recurring' ? 'Recurring' : null
  const d = new Date(g.deadline)
  if (isNaN(d.getTime())) return g.deadline
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>
}): Promise<Metadata> {
  const { slug } = await params
  const g = await grantBySlug(slug)
  if (!g) return { title: 'Grant not found' }

  const bits = [g.funding_type, g.cci_sector].filter(Boolean).join(' · ')
  const desc = (g.description ?? '').slice(0, 155).replace(/\s+\S*$/, '') + '…'
  return {
    title: g.name,
    description: desc,
    alternates: { canonical: `/grants/${slug}` },
    robots: shouldIndex(g) ? undefined : { index: false, follow: true },
    openGraph: {
      title: `${g.name} · Ona Funds`,
      description: bits ? `${bits}. ${desc}` : desc,
      url: `/grants/${slug}`,
      type: 'article',
      images: [OG_IMAGE],
    },
  }
}

export default async function GrantPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const g = await grantBySlug(slug)
  if (!g) notFound()

  const dl = daysLeft(g.deadline)
  const closed = dl !== null && dl < 0
  const urgent = dl !== null && dl >= 0 && dl <= 30
  const dead = g.link_state === 'dead'

  const who =
    g.eligibility_reviewed && g.eligible_who ? WHO_LABEL[g.eligible_who] ?? null : null
  const openTo = [who, ...eligibilityLabels(g.eligible_countries).slice(0, 6)].filter(Boolean)

  // Funder context and cross-links — all from grants already in the database.
  const [funder, { fromFunder, related }] = await Promise.all([
    funderBlurb(g.institution_id),
    relatedGrants(g),
  ])
  const funderHref = funder?.slug
    ? `/funders/${funder.slug}`
    : g.funder_id
      ? `/funders/${g.funder_id}`
      : null

  const verified = g.link_checked_at
    ? new Date(g.link_checked_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
    : null

  // schema.org/MonetaryGrant: tells a search engine this is a grant, from this
  // funder. Only the facts we actually hold; nothing invented.
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'MonetaryGrant',
    name: g.name,
    ...(g.description ? { description: g.description } : {}),
    ...(g.funder ? { funder: { '@type': 'Organization', name: g.funder } } : {}),
    ...(g.application_link ? { url: g.application_link } : {}),
    ...(g.eligible_countries?.length ? { areaServed: g.eligible_countries } : {}),
    isAccessibleForFree: true,
    mainEntityOfPage: `${SITE_URL}/grants/${slug}`,
  }

  return (
    <main className="mx-auto max-w-3xl px-5 py-12">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <BackLink
        href="/grants"
        className="text-xs font-bold uppercase tracking-[0.15em] text-[var(--terracotta)] underline-offset-4 hover:text-[var(--accent)] hover:underline"
      >
        ← All grants
      </BackLink>

      {/* Kicker */}
      <div className="mt-8 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs font-bold uppercase tracking-[0.18em] text-[var(--ink-soft)]">
        {g.funding_type && <span>{g.funding_type}</span>}
        {g.cci_sector && (
          <>
            <span className="text-[var(--line)]">/</span>
            <span>{g.cci_sector}</span>
          </>
        )}
      </div>

      <h1 className="mt-3 font-[family-name:var(--font-display)] text-[34px] leading-[1.05] sm:text-[48px]">
        {g.name}
      </h1>
      {g.funder && (
        <p className="mt-3 text-lg text-[var(--ink-2)]">
          {funderHref ? (
            <Link href={funderHref} className="underline underline-offset-4 hover:text-[var(--accent)]">
              {g.funder}
            </Link>
          ) : (
            g.funder
          )}
        </p>
      )}

      {closed && (
        <p className="mt-6 border-2 border-[var(--line)] bg-[var(--surface)] p-4 text-sm font-semibold">
          This call has closed. It is kept for reference; check the funder&rsquo;s page for the next round.
        </p>
      )}

      {/* Facts */}
      <dl className="mt-8 grid gap-px border border-[var(--ink)] bg-[var(--ink)] sm:grid-cols-2">
        {g.amount && (
          <div className="bg-[var(--bg)] p-5">
            <dt className="text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ink-soft)]">
              {/* A loan or investment is money to repay, not an award — never label it as one. */}
              {g.funding_type === 'loan' || g.funding_type === 'investment' ? 'Financing' : 'Award'}
            </dt>
            <dd className="mt-1 font-[family-name:var(--font-display)] text-xl leading-snug text-[var(--forest)]">
              {g.amount}
            </dd>
          </div>
        )}
        {deadlineText(g) && (
          <div className="bg-[var(--bg)] p-5">
            <dt className="text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ink-soft)]">Deadline</dt>
            <dd className={`mt-1 font-[family-name:var(--font-display)] text-xl ${urgent ? 'text-[var(--accent)]' : ''}`}>
              {deadlineText(g)}
              {urgent && (
                <span className="ml-2 text-[11px] font-bold uppercase tracking-[0.15em] text-[var(--accent)]">
                  {dl === 0 ? 'Closes today' : dl === 1 ? '1 day left' : `${dl} days left`}
                </span>
              )}
            </dd>
          </div>
        )}
        {openTo.length > 0 && (
          <div className="bg-[var(--bg)] p-5 sm:col-span-2">
            <dt className="text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ink-soft)]">Open to</dt>
            <dd className="mt-1 text-[15px] text-[var(--ink-2)]">
              {openTo.join(' · ')}
              {g.eligibility_reviewed && g.eligible_conditions ? ` — ${g.eligible_conditions}` : ''}
            </dd>
          </div>
        )}
      </dl>

      {g.description && (
        <div className="mt-8 space-y-4 text-[17px] leading-relaxed text-[var(--ink-2)]">
          {g.description
            .split(/\n{2,}/)
            .map((p) => p.trim())
            .filter(Boolean)
            .map((p, i) => (
              <p key={i}>{p}</p>
            ))}
        </div>
      )}

      {/* Apply */}
      {g.application_link && (
        <div className="mt-10">
          {dead && (
            <p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-[var(--ink-soft)]">
              ⚠ This link didn&rsquo;t respond when we last checked{verified ? ` on ${verified}` : ''}.
            </p>
          )}
          <TrackedLink
            href={g.application_link}
            target="_blank"
            rel="noopener noreferrer"
            event={{ name: 'grant_apply_click', grant: g.name, funder: g.funder, from: 'list' }}
            className={
              dead
                ? 'inline-block border-2 border-dashed border-[var(--line)] px-7 py-3.5 text-[14px] font-bold uppercase tracking-[0.06em] text-[var(--ink-soft)] transition-colors hover:border-[var(--accent)] hover:text-[var(--accent)]'
                : 'inline-block bg-[var(--accent)] px-7 py-3.5 text-[14px] font-bold uppercase tracking-[0.06em] text-[#121412] transition-colors hover:bg-[var(--ink)] hover:text-[var(--bg)]'
            }
          >
            {dead ? 'Try the funder’s page →' : 'Apply on the funder’s site →'}
          </TrackedLink>
        </div>
      )}

      {/* About the funder — the funder's own words, with a link to their full profile. */}
      {funder?.description && (
        <section className="mt-12 border-t border-[var(--line)] pt-8">
          <h2 className="text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ink-soft)]">
            About {funder.name}
          </h2>
          <p className="mt-3 text-[16px] leading-relaxed text-[var(--ink-2)]">
            {funder.description.length > 320
              ? funder.description.slice(0, 320).replace(/\s+\S*$/, '') + '…'
              : funder.description}
          </p>
          {funderHref && (
            <Link
              href={funderHref}
              className="mt-3 inline-block text-xs font-bold uppercase tracking-[0.12em] text-[var(--terracotta)] underline-offset-4 hover:text-[var(--accent)] hover:underline"
            >
              View {funder.name}&rsquo;s profile →
            </Link>
          )}
        </section>
      )}

      {/* More from this funder */}
      {fromFunder.length > 0 && (
        <section className="mt-12 border-t border-[var(--line)] pt-8">
          <h2 className="text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ink-soft)]">
            More from {funder?.name ?? g.funder}
          </h2>
          <div className="mt-4">
            <GrantList items={fromFunder} />
          </div>
        </section>
      )}

      {/* Related opportunities — same sector or open to the same place. */}
      {related.length > 0 && (
        <section className="mt-12 border-t border-[var(--line)] pt-8">
          <h2 className="text-[10px] font-bold uppercase tracking-[0.2em] text-[var(--ink-soft)]">
            Related opportunities
          </h2>
          <div className="mt-4">
            <GrantList items={related} showFunder />
          </div>
        </section>
      )}

      {verified && (
        <p className="mt-12 border-t border-[var(--line)] pt-6 text-xs text-[var(--ink-3)]">
          Ona checks every listing. This one&rsquo;s link was last verified on {verified}. Amounts,
          deadlines and eligibility are the funder&rsquo;s own; always confirm on their page before applying.
        </p>
      )}
    </main>
  )
}
